<?php

namespace TaxeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaxeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxeRepository extends EntityRepository
{
}
