<?php

namespace ContractBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends EntityRepository
{
    public function findAllUnitContract()
    {
        return $this->createQueryBuilder('self')
            ->where('self.unit IS NOT NULL')
            ->andWhere('self.parking IS NULL')
            ->getQuery()
            ->getResult();
    }
    
    public function findAllParkingContract()
    {
        return $this->createQueryBuilder('self')
            ->where('self.parking IS NOT NULL')
            ->andWhere('self.unit IS NULL')
            ->getQuery()
            ->getResult();
    }
    
    public function findSpecialContract()
    {
        return $this->createQueryBuilder('self')
            ->where('self.parking IS NOT NULL')
            ->andWhere('self.unit IS NOT NULL')
            ->getQuery()
            ->getResult();
    }
}
